### ISSUE TITLE
Implement XRSound

### ISSUE THREAD

**Issue by jalexb88** [orbiternassp/NASSP#474]
As we know, OrbiterSound 4.0 is not officially compatible with Orbiter 2016. While it does run without too many issues, there are some good reasons to make the switch, such as (not limited to) these issues: 

- 3D audio causing low frame-rate at session start until a sound is played. 
- Weird rumbling noise heard around the time of pitch-over during P64 . 
- Radio/mp3 Panel MFD causes a CTD

XRSound: https://www.alteaaerospace.com/ is the best candidate right now for a new sound solution for NASSP. Currently OrbiterSound is deeply intertwined in NASSP code so it will require a fair amount of work to successfully transition over to XRSound but the in the long run this should be good sound platform for NASSP 8.0+

**Comment by Thymo-** [comment]
Would it be a good idea to hook up XRSound in a way so that it can be easily replaced again if at all possible?
Just in case something like this were ever to happen again.

**Comment by eddievhfan1984** [comment]
XRSound does have a wrapper module for OrbiterSound calls, although its success is kinda marginal, IMO. But I haven’t seen any buzz about whether or not OrbiterSound 4.x for 2016 is dead in the water.

**Comment by dseagrav** [comment]
If you decide to do this I need to know about it before you commit so I can repack the autobuild resource bundle with xrsound instead of orbitersound.

**Comment by jalexb88** [comment]
> If you decide to do this I need to know about it before you commit so I can repack the autobuild resource bundle with xrsound instead of orbitersound.

Sounds good. It will probably take a while before we get it implemented but we'll coordinate it with you when the time comes.

**Comment by ethhics** [comment]
With [OrbiterSound 5.0](http://orbiter.dansteph.com/forum/index.php?topic=14499.0) complete, which supports Orbiter 2016, is there still a need for a port to XRSound?

**Comment by CaptainSwag101** [comment]
Bumping because if we plan to target OpenOrbiter for future releases, OrbiterSound 5.0 uses an incompatible runtime library (static vs. dynamic runtime) that causes (as far as I can tell) unfixable linking errors. I don't really have the skills personally to execute such a conversion on my own, but after three days of work I am still unable to link both OrbiterSDK and OrbiterSound, only one or the other. Not only that, but OpenOrbiter natively implements XRSound, so a conversion to that sound engine would be a sensible thing to do IMO.

**Comment by rcflyinghokie** [comment]
https://github.com/orbiternassp/NASSP/pull/1170

**Comment by CaptainSwag101** [comment]
Closed via #1170.
