### ISSUE TITLE
LM Cabin temps high with crew in cabin

### ISSUE THREAD

**Issue by jalexb88** [orbiternassp/NASSP#496]
The LM ECS has become quite stable with commit #493 however, while the suit temps are quite stable, the cabin temps will climb quite high (100+ F) when the crew is  placed "in cabin" on the PAMFD ECS page. For now there is no real way of having normal cabin temperatures other then always having the CDR and LMP "in suit" or "PLSS" One possible theory is that the hot air in the cabin is not properly being expelled to the coolant loops. More investigation will be required to find the issue.

**Comment by rcflyinghokie** [comment]
I believe part of the problem is after LM 3, the cabin was not connected to the coolant loops via the cabin fan, it appeared to just be at the mercy of the suit circuit and radiative cooling.  I will investigate further and begin massaging a solution.

In the mean time I have reduced cabin heating due to lighting/cabin fan.
